### ISSUE TITLE
Link errors building with build.sh

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-tools#10]
The build instructions in BUILDING.md are out of date — the shell scripts have been moved to the `ci/` directory. This has caused customer confusion.

More seriously, the build fails at the link stage with a fatal error; apparently it is trying to write the output to a file `cblite` when there is already a directory at the same path. The below output comes from Linux, but I got the same error on macOS.

```
[100%] Linking CXX executable cblite
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../bin/ld: cannot open output file cblite: Is a directory
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by borrrden** [comment]
Both items addressed in 6bfb0ca19bf7286293fd4dee90d6dd5ae9aef2e6
