### ISSUE TITLE
cblite: N1QL parse fails with `AND` after `END`

### ISSUE THREAD

**Issue by borrrden** [couchbaselabs/couchbase-mobile-tools#14]
The following query fails to parse:

<pre style="color:red">SELECT name WHERE ANY review IN reviewList SATISFIES review=&#39;review2042&#39; END AND NOT (unitPrice&lt;10) AND test_id=&#39;where_func&#39; ORDER BY name
                                                                             ^^
N1QL syntax error
Error parsing N1QL
</pre>

Note that the following query succeeds:

<pre style="color:red">SELECT name, reviewList FROM product WHERE (EVERY review in product.reviewList SATISFIES length(review)&gt;9 END) AND test_id=&quot;where_func&quot; ORDER BY name limit 3</pre>

The latter has the array triad inside of parenthesis

**Comment by snej** [comment]
Fixed in a7c95c83d5368e2648b91fd02242f93b632a4164 ... it was a problem with operator precedence in the grammar.
