### ISSUE TITLE
cblite+query: Error: N1QL syntax error near character

### ISSUE THREAD

**Issue by Dushistov** [couchbaselabs/couchbase-mobile-tools#16]
Something wrong with documentation or cblite.
According to README.cblite.md `query --limit 10 '["=", [".type"], "airline"]'` should works:
```sh
$  cblite travel-sample.cblite2
(cblite) query --limit 10 '["=", [".type"], "airline"]'
```

in reality:

```
evgeniy@15inch /tmp/couchbase-mobile-tools/build $ ./cblite /tmp/test.cblite2
Opened read-only database /tmp/test.cblite2/
(cblite) query --limit 10 '["=", [".type"], "airline"]'
               ^
Error: N1QL syntax error near character 1
Error: N1QL syntax error near character 1
(cblite) query '["=", [".type"], "airline"]'
               ^
Error: N1QL syntax error near character 1
```

**Comment by Dushistov** [comment]
I should add that `cat` and `ls` sub-commands work fine, so this is valid `.cblite2` file.

**Comment by snej** [comment]
The JSON doesn't need to be quoted anymore, and in fact it doesn't parse correctly if quoted. So just remove the single-quotes from your command line. I'll fix the README.

I'm not sure whether it's worth it to add code to detect and strip the quotes.
