### ISSUE TITLE
`cp` should support TLS/SSL replication

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-mobile-tools#2]
The replicator in the `cblite` tool does not support TLS.

This is because it provides its own C4Socket implementation, having no Couchbase Lite layer to provide it. For this we use civetweb as a lightweight cross-platform HTTP/WebSocket library. Unfortunately the TLS support in civetweb is (IIRC) difficult to configure since it uses OpenSSL. We never enabled it because we didn't need it for unit tests and we decided it was too heavyweight to build into CBL. But we should enable it in the `litecore` tool.

(Moved here from https://github.com/couchbase/couchbase-lite-core/issues/587)

**Comment by rajagp** [comment]
Also came up as a request from a customer who are using this for internal testing. So would be great to see this resolved at some point

**Comment by snej** [comment]
@borrrden points out that another reason not to use OpenSSL is its [poor security/quality record](
https://www.cvedetails.com/vulnerability-list/vendor_id-217/product_id-383/opdos-1/Openssl-Openssl.html). We like [mbed TLS](https://tls.mbed.org/) a lot better, but its API is very different.

**Comment by borrrden** [comment]
Just came across this again, how is the story different now?

**Comment by snej** [comment]
Should Just Work, now that we're using BuiltinWebSocket.
