### ISSUE TITLE
cannot build on Mac OS X (10.14.6/Mojave)

### ISSUE THREAD

**Issue by garyhooper** [couchbaselabs/couchbase-mobile-tools#21]
When trying to build on OS X, I encounter the following errors:
```CMake Error at CMakeLists.txt:3 (project):
  Generator

    Unix Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```
How do I properly set up to build on a Mac?

**Comment by snej** [comment]
I've never seen an error like that. What version of CMake do you have? How did you install it?

**Comment by garyhooper** [comment]
I'm using 3.16.2, installed via the DMG from cmake.org. (Command-line tools are installed from this; using `sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install`

**Comment by borrrden** [comment]
Try running the interactive build script if you need help building it (as noted in the README)

**Comment by garyhooper** [comment]
The above error was produced when running the interactive `build.py` script.

**Comment by borrrden** [comment]
Sorry about that, I had fixed this error before but it got lost somewhere while developing locally on two different systems for testing.  This should be fixed in daa36c9bd06d4fcdb3e6db1c595afcecd0ff191b

**Comment by garyhooper** [comment]
I pulled the latest version. The above errors disappeared, but I now encounter:
```
CMake Error at CMakeLists.txt:23 (add_subdirectory):
  The source directory

    /Users/gary/Developer/couchbase-mobile-tools-master/vendor/couchbase-lite-core

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/Users/gary/Developer/couchbase-mobile-tools-master/bin/cbl-log/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target `cbl-log'.  Stop.
```

**Comment by snej** [comment]
Did you run `git submodule init` and `git submodule update` after checkout?

**Comment by garyhooper** [comment]
I had "downloaded" the project. If I instead "clone" it, I can build successfully.  Thanks for the above tip on the submodule.

**Comment by borrrden** [comment]
There are very few times that I can recommend downloading instead of git cloning.  There are simply no advantages to using the GitHub download feature that I can think of.  It only has downsides like this one.
