### ISSUE TITLE
cblite ls Pattern matching is broken

### ISSUE THREAD

**Issue by amrishraje** [couchbaselabs/couchbase-mobile-tools#25]
looks like Pattern matching in ls is not working as expected. It provides the opposite result of what I expect. 

e.g. cblite ls syncdb.cblite2
Customer::87738_157     Customer::895206_157    Customer::970450_157    Route::38083_157

cblite ls syncdb.cblite2 Customer::87738_15
Customer::895206_157    Customer::970450_157    Route::38083_157

cblite ls syncdb.cblite2 Route*
Customer::895206_157    Customer::970450_157

cblite ls syncdb.cblite2 *
(No documents with IDs matching "*")

Looks like the matching is putting in a NOT by default

**Comment by snej** [comment]
It looks like you're running these commands from a shell, not the tool's interactive mode. In that case you have to quote the asterisks, or the shell will try to expand them against filenames.

**Comment by amrishraje** [comment]
Tried to quote it as well as with the tool's interactive mode. In both cases, what I find is the tool is treating the match pattern with a NOT condition. I get back documents that do not match the pattern I specify and the matching docs are skipped!!

C:\Users\09270742\node_modules\cblite-cli-win\bin>cblite ls syncdb.cblite2
Route::97544_157_1      Route::97544_157_3      Route::97544_157_4      Route::97545_157
RouteToSalesUnit::1234_567                      RouteToSalesUnit::97545_157
public_doc:1

C:\Users\09270742\node_modules\cblite-cli-win\bin>cblite ls syncdb.cblite2 "Route*"
public_doc:1

C:\Users\09270742\node_modules\cblite-cli-win\bin>cblite syncdb.cblite2
Opened read-only database .\syncdb.cblite2\
(cblite) ls
Route::97544_157_1      Route::97544_157_3      Route::97544_157_4      Route::97545_157
RouteToSalesUnit::1234_567                      RouteToSalesUnit::97545_157
public_doc:1
(cblite) ls Route*
public_doc:1
(cblite)

**Comment by borrrden** [comment]
Opened [CBL-976](https://issues.couchbase.com/browse/CBL-976) to track this, but it will unfortunately be low priority since cblite is an unsupported product.

**Comment by snej** [comment]
This may be Windows-specific; I just tried the `ls` command with wildcards on macOS and it works fine. We may be using a platform-specific system function to do the wildcard-matching, and the bug is in the Windows side of that?

**Comment by amrishraje** [comment]
> This may be Windows-specific; I just tried the `ls` command with wildcards on macOS and it works fine. We may be using a platform-specific system function to do the wildcard-matching, and the bug is in the Windows side of that?

I can confirm that ls command with wildcards works find on Linux. Looks like this is a windows specific bug.
