### ISSUE TITLE
CBlite CLI issue with  -cacert flag in windows

### ISSUE THREAD

**Issue by srinivasyp** [couchbaselabs/couchbase-mobile-tools#32]
I am trying to pass pem file using the –cacert flag in below command but getting errors , Please advise how to pass the pem file in CLI

Example
cblite cp --cacert<prod.cert> --user <uid>:<pwd> -v wss://<prod_url>/syncdb

**Comment by borrrden** [comment]
This reads like a question.  If this is a question please post it on the [forums](https://forums.couchbase.com/c/mobile/14).  Otherwise, if this is a bug report then please include the actual errors you face and why you think they are a bug in the product.
