### ISSUE TITLE
Opening encrypted databases 2.8 with cblite

### ISSUE THREAD

**Issue by jpval69** [couchbaselabs/couchbase-mobile-tools#39]
Hello,
My app uses the .Net Couchbase Lite Enterprise 2.8.6 SDK and the encryption works great. 
when I use my encryption key with cblite.exe,  I get the following error.
cblite.exe --encrypted mabase.cblite2
Database password or hex key:
13:57:48.003790| [DB] ERROR: SQLite error (code 26): file is not a database in "SELECT count(*) FROM sqlite_master"
13:57:48.005162| [DB] ERROR: {DB#1} Could not decrypt database with AES256
I have downloaded cblite.exe from this link
https://github.com/couchbaselabs/couchbase-mobile-tools/releases/tag/cblite-2.8EE-alpha
Can you explain me the problem ?
Thanks

**Comment by borrrden** [comment]
I think this is the result of not having guaranteed compatibility between platforms with regards to encryption.  This is something that was sort of addressed recently down in couchbase-lite-core by adding another method of decryption but in 2.8 I suspect you might not be able to open encrypted .NET DBs at all.  

As a workaround, you could potentially write a small .NET desktop program that decrypted the database first.  I know that's annoying, but probably better than nothing.

**Comment by jpval69** [comment]
OK I note the bypass... We have a Desktop application which decrypts the database, but I wanted to avoid long decryption step for large databases. Thank you for your reply.

**Comment by borrrden** [comment]
Yes I can definitely understand how that is an issue and I filed [a ticket](https://issues.couchbase.com/browse/CBL-2819) to get this fixed.

**Comment by borrrden** [comment]
This was fixed in the [VSCode Plugin](https://marketplace.visualstudio.com/items?itemName=Couchbase.vscode-cblite) that I made but I can't remember if it was fixed here or not.
