### ISSUE TITLE
Docs - bubble up Query --explain

### ISSUE THREAD

**Issue by househippo** [couchbaselabs/couchbase-mobile-tools#40]
I poked around and found what I needed.
I'm sure other would like to use the CBL-Tool to do the same.

> (cblite) query --explain SELECT * FROM _
> SELECT fl_result(fl_root(_.body)) FROM kv_default AS _ WHERE (_.flags & 1 = 0)
> 
> 2|0|0| SCAN TABLE kv_default AS _
> 
> {"FROM":[{"COLLECTION":"_"}],"WHAT":[["."]]}

**Comment by borrrden** [comment]
I don't understand what this is getting at.

**Comment by Fujio-Turner** [comment]
@borrrden .... Its about documentation and samples / example code of how to do the operation.

**Comment by snej** [comment]
`cblite` is an unofficial tool and most of the documentation is in the `help` command. If you run `help query` it'll show the `--explain` flag.
