### ISSUE TITLE
cblite - use session tokens for authentication

### ISSUE THREAD

**Issue by cb-davidelliott** [couchbaselabs/couchbase-mobile-tools#41]
We have below requirements in CB database as part of our project, would require your help on the same.

1. Authorizing using session token - Currently we are using below userID-password authentication CLI command to generate continues pull replication.
cblite cp --continuous -v --user userID:password -v <syncgatewayURL> dbname.cblite2

Now we are changing authentication method using session tokens.

It appears that cblite does not allow user authentication with session tokens.
Can the ability to authenticate with session tokens be added to cblite?

**Comment by pasin** [comment]
I have created https://issues.couchbase.com/browse/CBL-2939.
