### ISSUE TITLE
cant do cmake on ubuntu 22.04

### ISSUE THREAD

**Issue by ridhoyp** [couchbaselabs/couchbase-mobile-tools#60]
[ 74%] Building CXX object LiteCore/CMakeFiles/LiteCoreObjects.dir/Replicator/DatabaseCookies.cc.o
make[3]: *** [LiteCore/CMakeFiles/LiteCoreObjects.dir/build.make:1168: LiteCore/CMakeFiles/LiteCoreObjects.dir/Replicator/ChangesFeed.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/Checkpointer.hh:14,
                 from /root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/Checkpointer.cc:14:
/root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/ReplicatorTypes.hh:133:16: error: ‘numeric_limits’ is not a member of ‘std’
  133 |         = std::numeric_limits<CollectionIndex>::max();
      |                ^~~~~~~~~~~~~~
/root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/ReplicatorTypes.hh:133:46: error: expected primary-expression before ‘>’ token
  133 |         = std::numeric_limits<CollectionIndex>::max();
      |                                              ^
/root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/ReplicatorTypes.hh:133:49: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  133 |         = std::numeric_limits<CollectionIndex>::max();
      |                                                 ^~~
      |                                                 std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /root/couchbase-mobile-tools/vendor/couchbase-lite-core/vendor/fleece/API/fleece/slice.hh:18,
                 from /root/couchbase-mobile-tools/vendor/couchbase-lite-core/C/include/c4Error.h:21,
                 from /root/couchbase-mobile-tools/vendor/couchbase-lite-core/C/include/c4Base.h:15,
                 from /root/couchbase-mobile-tools/vendor/couchbase-lite-core/C/Cpp_include/c4Base.hh:21,
                 from /root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/Checkpointer.cc:13:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make[3]: *** [LiteCore/CMakeFiles/LiteCoreObjects.dir/build.make:1196: LiteCore/CMakeFiles/LiteCoreObjects.dir/Replicator/Checkpointer.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:378: LiteCore/CMakeFiles/LiteCoreObjects.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:307: CMakeFiles/cblite.dir/rule] Error 2
make: *** [Makefile:169: cblite] Error 2

***********************************************************************************************************************************************************************************************************************
To call this build non-interactively, next time use build.py --debug cblite
***********************************************************************************************************************************************************************************************************************

**Comment by borrrden** [comment]
Yes, I've seen this and it's probably a case of a missing include.  If you find out what it is let me know but otherwise I will get to it soon.

**Comment by ridhoyp** [comment]
Hi i add at header  :

#include <limits>
#include <limits.h>


in this files :

/root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/ReplicatorTypes.hh
/root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/Checkpointer.hh
/root/couchbase-mobile-tools/vendor/couchbase-lite-core/Replicator/Checkpointer.cc

and its ok now, thanks for help

**Comment by borrrden** [comment]
Thanks!  This feels familiar and it might just be that the submodule on this repo is out of date.  On our build servers, it doesn't track the submodule and instead checks out the `release/master` branch of LiteCore.
