### ISSUE TITLE
Can't run cblite on macOS Ventura 

### ISSUE THREAD

**Issue by wongk990** [couchbaselabs/couchbase-mobile-tools#65]
I downloaded macOS_86_64.zip on an M1 and I'm getting a seg fault when running `cblite cp *.json test.cblite2`

```[1]    97078 segmentation fault  cblite cp resources test.cblite2```

![IEXP-@2x](https://user-images.githubusercontent.com/106693811/223214140-b9ffec39-037f-4a3b-ab5b-c72ebeb72871.png)

**Comment by borrrden** [comment]
Is this still true for the latest release?
