### ISSUE TITLE
cblite: array_agg does not work

### ISSUE THREAD

**Issue by TheCrazyT** [couchbaselabs/couchbase-mobile-tools#69]
was using something similar to:
`SELECT a,array_agg(b) FROM _default AS a LEFT JOIN _default AS b ON b.a_id=Meta(a).id GROUP BY a`

The cblite tool throws an exception "[SQL] ERROR: array_agg: exception!".

Was trying to debug it with gdb.
Internal it seem to pass a integer-key dict to the array_agg function and fails about non-set shared keys.
(will post source location later, not enough time for it atm)

**Comment by TheCrazyT** [comment]
Basically the main exception seems to be thrown on the "fleece" library:

https://github.com/couchbase/fleece/blob/33710241d9115620ff89567bc59060041f9f3394/Fleece/Core/Encoder.cc#L638

**Comment by snej** [comment]
This is an issue with Couchbase Lite Core, not the cblite tool. Please file an issue on [Jira](https://issues.couchbase.com/projects/CBL/issues).
